(function(){
'use strict';
const ROLE='lineLogicWizzPreviewRole',TOKEN='lineLogicWukMasterToken',AUTH='https://aavinfwtnbwforbkgrzh.supabase.co/auth/v1',KEY='sb_publishable_Ot5qtj32uOZWxY9Z4G6T2g_jXmXi2il',QUIZ='https://line-logic-pop-quiz.addotbradford.workers.dev';
const overlay=document.getElementById('accessOverlay'),form=document.getElementById('masterLoginForm');
const MASTER_PROFILES=Object.freeze({'addotbradford@gmail.com':{name:'Antony',initials:'AB'},'duncan.vaux@wizzair.com':{name:'Duncan',initials:'DV'}});
let role=null,masterToken=null,accountProfile=null;
function read(key){try{return sessionStorage.getItem(key)}catch{return null}}
function save(key,value){try{value?sessionStorage.setItem(key,value):sessionStorage.removeItem(key)}catch{}}
async function verifiedRole(token){const account=await fetch(AUTH+'/user',{headers:{apikey:KEY,Authorization:'Bearer '+token}});if(!account.ok)throw new Error('Please sign in again.');const user=await account.json();if(!user.id||!user.email_confirmed_at||user.is_anonymous)throw new Error('Please confirm your email before signing in.');const next=await verify(token)?'admin':'user';if(next==='user'){const membership=await fetch(QUIZ+'/api/progress',{headers:{Authorization:'Bearer '+token}});const record=await membership.json();if(!membership.ok)throw new Error(record.error||'This account has not been invited.');if(!record.profile?.setup_completed)throw new Error('Complete your account setup using your invitation email first.');}const metadata=user.user_metadata||{};const name=String(metadata.first_name||metadata.display_name||metadata.full_name||'').trim();const accountEmail=user.email?.toLowerCase()||'';accountProfile=next==='admin'&&Object.hasOwn(MASTER_PROFILES,accountEmail)?MASTER_PROFILES[accountEmail]:{name:name.split(/\s+/)[0]||'',initials:String(metadata.initials||name.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join('')).toUpperCase()};return next;}
async function verify(token){const response=await fetch(QUIZ+'/api/wuk-master',{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw new Error('Master account verification is unavailable.');return (await response.json()).master===true;}
function unlock(next,fresh){role=next;if(next==='admin'&&new URLSearchParams(location.search).get('hostQuiz')==='1'){location.replace(QUIZ+'/admin/sign-in#wuk_access_token='+encodeURIComponent(masterToken));return;}const greeting=document.getElementById('accountGreeting');if(greeting){const hour=new Date().getHours();const period=hour<12?'morning':hour<18?'afternoon':'evening';greeting.textContent='Good '+period+(accountProfile?.name?', '+accountProfile.name:'');}document.documentElement.dataset.lineLogicRole=next;document.body.classList.remove('access-locked');if(overlay)overlay.hidden=true;document.querySelector('.session-control')?.remove();
 const control=document.createElement('aside');control.className='session-control';control.setAttribute('aria-label','Current Line Logic access');const label=document.createElement('span');label.className='session-role';label.textContent=next==='admin'?'MASTER':'USER';control.append(label);
 if(next==='admin'){const link=document.createElement('a');link.className='session-master-link';link.textContent='Host Quiz';link.href=QUIZ+'/admin/sign-in#wuk_access_token='+encodeURIComponent(masterToken);control.append(link);}
 const progressLink=document.createElement('a');progressLink.className='session-master-link';progressLink.textContent='My Progress';progressLink.href='progress.html';control.append(progressLink);
 const out=document.createElement('button');out.className='session-sign-out';out.type='button';out.textContent='Sign out'+(accountProfile?.initials?' '+accountProfile.initials:'');out.onclick=async()=>{const token=masterToken;save(ROLE,null);save(TOKEN,null);if(token){try{await fetch(AUTH+'/logout',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token}})}catch{}}location.replace(QUIZ+'/sign-out');};control.append(out);(document.querySelector('.site-session-slot')||document.body).append(control);
 requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('lineLogicAccessGranted',{detail:{freshLogin:fresh}})));
}
function show(){if(!overlay){location.replace('./?login=1');return}overlay.hidden=false;document.body.classList.add('access-locked');document.getElementById('masterEmail').focus();}
window.LineLogicAccess=Object.freeze({getRole:()=>role,isAdmin:()=>role==='admin'});
if(form)form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button'),message=document.getElementById('masterLoginMessage'),password=document.getElementById('masterPassword');button.disabled=true;message.textContent='Signing in…';try{
 const response=await fetch(AUTH+'/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('masterEmail').value.trim(),password:password.value})});password.value='';const data=await response.json();if(!response.ok||!data.access_token)throw new Error('Email or password was not recognised.');const next=await verifiedRole(data.access_token);masterToken=data.access_token;save(TOKEN,masterToken);save(ROLE,'user');message.textContent='';unlock(next,true);
 }catch(error){password.value='';message.textContent=error.message||'Unable to sign in.';}finally{button.disabled=false;}};
(async()=>{if(new URLSearchParams(location.search).get('signout')==='1'){const token=read(TOKEN);save(TOKEN,null);save(ROLE,null);if(token){try{await fetch(AUTH+'/logout',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token}})}catch{}}history.replaceState(null,'',location.pathname+'?login=1');show();return;}if(new URLSearchParams(location.hash.slice(1)).get('type')==='recovery'||new URLSearchParams(location.search).get('login')==='1'){show();return;}const token=read(TOKEN);if(token){try{const next=await verifiedRole(token);masterToken=token;unlock(next,false);return;}catch{save(TOKEN,null);save(ROLE,null);}}show();})();
})();
