(function(){
'use strict';
if(window.LineLogicSession)return;
const QUIZ='https://line-logic-pop-quiz.addotbradford.workers.dev',HOME='https://linelogic.uk/wuk/',AUTH='https://aavinfwtnbwforbkgrzh.supabase.co/auth/v1',KEY='sb_publishable_Ot5qtj32uOZWxY9Z4G6T2g_jXmXi2il';
const TOKEN=location.origin===QUIZ?'lineLogicQuizAccessToken':'lineLogicWukMasterToken',REFRESH='lineLogicRefreshToken',LAST='lineLogicLastActivity',IDLE=900000;
let pending=null,ended=false,generation=0,heartbeatAt=0,activityAt=0,trailing=null;
const read=k=>sessionStorage.getItem(k),save=(k,v)=>v?sessionStorage.setItem(k,String(v)):sessionStorage.removeItem(k);
const emit=()=>{window.dispatchEvent(new Event('lineLogicQuizSessionChanged'));window.dispatchEvent(new Event('lineLogicSessionUpdated'));};
function capture(){const p=new URLSearchParams(location.hash.slice(1)),token=p.get('wuk_access_token');if(!token)return;save(TOKEN,token);save(REFRESH,p.get('wuk_refresh_token'));const last=Number(p.get('wuk_last_activity'));save(LAST,last>0&&last<=Date.now()?last:Date.now());['wuk_access_token','wuk_refresh_token','wuk_last_activity'].forEach(k=>p.delete(k));history.replaceState(null,'',location.pathname+location.search+(p.size?'#'+p.toString():''));}
function clear(){const old=read(TOKEN);if(old){fetch(QUIZ+'/api/account-session',{method:'DELETE',headers:{Authorization:'Bearer '+old},keepalive:true}).catch(()=>{});fetch(AUTH+'/logout?scope=local',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+old},keepalive:true}).catch(()=>{});}generation++;ended=true;[TOKEN,REFRESH,LAST,'lineLogicWizzPreviewRole'].forEach(k=>save(k,null));emit();}
function logout(idle){const token=read(TOKEN);clear();if(token){fetch(QUIZ+'/api/account-session',{method:'DELETE',headers:{Authorization:'Bearer '+token},keepalive:true}).catch(()=>{});fetch(AUTH+'/logout?scope=local',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token},keepalive:true}).catch(()=>{});}if(location.origin===QUIZ)fetch('/api/host-session',{method:'DELETE',keepalive:true}).catch(()=>{});location.replace(HOME+'?login=1'+(idle?'&expired=1':''));}
function expired(){return !!read(TOKEN)&&Date.now()-Number(read(LAST))>=IDLE;}
async function validToken(){if(ended||!read(TOKEN))return null;if(expired()){logout(true);throw new Error('Signed out after 15 minutes of inactivity.');}const token=read(TOKEN);let exp=0;try{exp=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).exp*1000;}catch{}if(!exp||exp-Date.now()>120000)return token;if(!read(REFRESH)){logout(false);throw new Error('Please sign in again.');}if(pending)return pending;const stamp=generation;pending=(async()=>{const response=await fetch(AUTH+'/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:read(REFRESH)})});const data=await response.json();if(!response.ok||!data.access_token){if(response.status>=500)throw new Error('Unable to renew your login.');logout(false);throw new Error('Please sign in again.');}if(ended||generation!==stamp)throw new Error('Session ended.');if(expired()){logout(true);throw new Error('Session ended.');}save(TOKEN,data.access_token);save(REFRESH,data.refresh_token);emit();return data.access_token;})().finally(()=>{pending=null;});return pending;}
async function heartbeat(){if(ended||!read(TOKEN)||Date.now()-heartbeatAt<5000)return;heartbeatAt=Date.now();try{const token=await validToken();if(!token)return;const r=await fetch(QUIZ+'/api/account-session',{method:'POST',headers:{Authorization:'Bearer '+token}});if(r.status===401){logout(true);return;}if(r.ok&&location.origin===QUIZ)await fetch('/api/host-session',{method:'PUT',headers:{Authorization:'Bearer '+token}});}catch{}}
function adoptSession(data){ended=false;generation++;save(TOKEN,data.access_token);save(REFRESH,data.refresh_token);save(LAST,Date.now());heartbeatAt=0;emit();heartbeat();}
function activity(event){if(!event.isTrusted||document.visibilityState==='hidden'||!read(TOKEN)||ended)return;if(expired()){logout(true);return;}if(Date.now()-activityAt<500)return;activityAt=Date.now();save(LAST,Date.now());heartbeat();clearTimeout(trailing);trailing=setTimeout(heartbeat,5100);}
function handoff(value){const u=new URL(value,location.href);const trusted=(u.origin===new URL(HOME).origin&&u.pathname.startsWith('/wuk'))||u.origin===QUIZ||(u.origin==='https://addotbradford-afk.github.io'&&u.pathname.startsWith('/LL001/'));if(!trusted||u.origin===location.origin||!read(TOKEN))return u.href;const p=new URLSearchParams(u.hash.slice(1));p.set('wuk_access_token',read(TOKEN));if(read(REFRESH))p.set('wuk_refresh_token',read(REFRESH));p.set('wuk_last_activity',read(LAST)||Date.now());u.hash=p.toString();return u.href;}
capture();if(read(TOKEN)&&!read(LAST))save(LAST,Date.now());
window.LineLogicSession=Object.freeze({validToken,adoptSession,logout,clear,handoff});
['pointerdown','pointermove','keydown','touchstart','wheel','scroll'].forEach(name=>document.addEventListener(name,activity,{capture:true,passive:true}));
document.addEventListener('click',event=>{const a=event.target.closest?.('a[href]');if(a&&read(TOKEN)){a.referrerPolicy='no-referrer';a.href=handoff(a.href);}},true);
function check(){if(!read(TOKEN)||ended)return;if(expired()){logout(true);return;}if(document.visibilityState!=='hidden')validToken().catch(()=>{});}
window.addEventListener('pageshow',check);document.addEventListener('visibilitychange',check);setInterval(check,5000);
if(read(TOKEN)){fetch(QUIZ+'/api/account-session',{headers:{Authorization:'Bearer '+read(TOKEN)}}).then(r=>{if(r.status===401)validToken().then(token=>fetch(QUIZ+'/api/account-session',{headers:{Authorization:'Bearer '+token}})).then(next=>{if(next.status===401)logout(true);}).catch(()=>{});}).catch(()=>{});check();}
})();
