(function(){
'use strict';
const API='https://line-logic-pop-quiz.addotbradford.workers.dev/api/progress';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let selected='',nextOffset=null;
async function request(path='',options={}){const token=sessionStorage.getItem('lineLogicWukMasterToken');const response=await fetch(API+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load progress.');return data;}
function historyHTML(events){return events.map(event=>{const date=new Date(event.created_at).toLocaleString('en-GB');const archived=event.archived?' · Archived before reset':'';if(event.kind==='scenario')return '<article class="progress-event"><time>'+esc(date)+'</time><h3>'+esc(event.title)+archived+'</h3><p>Scenario opened.</p></article>';const d=event.details;return '<details class="progress-event"><summary>'+esc(event.title)+' · '+esc(d.correct)+' / '+esc(d.total)+' correct'+archived+'</summary><p>'+esc(date)+' · '+esc(d.answered)+' questions answered</p>'+d.questions.map(q=>'<article class="progress-answer"><h3>'+esc(q.question)+'</h3><p class="'+(q.correct?'correct':'incorrect')+'">'+(q.correct?'Correct':q.answered?'Needs practice':'Not answered')+'</p><p>Your answer: '+esc(q.answer)+'</p><p>Correct answer: '+esc(q.correctAnswer)+'</p>'+(q.elapsedMs!==null?'<p>Answer time: '+esc((q.elapsedMs/1000).toFixed(1))+' seconds</p>':'')+'</article>').join('')+'</details>';}).join('');}
async function load(append=false){const message=document.getElementById('progressMessage');message.textContent='Loading…';try{const params=new URLSearchParams();if(selected)params.set('userId',selected);if(document.getElementById('includeArchivedProgress')?.checked)params.set('includeArchived','1');if(append&&nextOffset!==null)params.set('offset',nextOffset);const data=await request('?'+params);document.getElementById('progressOwner').textContent=(data.profile.first_name+' '+data.profile.surname).trim()+' · '+data.profile.email;const summary=data.summary||{};document.getElementById('progressSummary').innerHTML=[['Scenarios opened',summary.scenarios||0],['Solo rounds completed',summary.rounds||0],['Questions answered',summary.answered||0],['Correct answers',summary.correct||0]].map(([label,count])=>'<div class="progress-stat"><strong>'+esc(count)+'</strong><span>'+esc(label)+'</span></div>').join('');const history=document.getElementById('progressHistory');if(append)history.insertAdjacentHTML('beforeend',historyHTML(data.events));else history.innerHTML=data.events.length?historyHTML(data.events):'<p>No progress saved yet. Open a scenario or finish a single-player quiz to begin.</p>';nextOffset=data.nextOffset;document.getElementById('loadMoreProgress').hidden=nextOffset===null;message.textContent=data.master&&data.resets?.length?'Last tracker reset: '+new Date(data.resets[0].created_at).toLocaleString('en-GB')+'.':'';return data;}catch(error){message.textContent=error.message;}}
window.addEventListener('lineLogicProgressReset',()=>void load());
window.addEventListener('lineLogicAccessGranted',async()=>{const data=await load();if(!data?.master)return;try{const people=await request('?users=1');const select=document.getElementById('progressUser');select.innerHTML=people.users.map(p=>'<option value="'+esc(p.user_id)+'">'+esc(p.first_name+' '+p.surname+' · '+p.email)+'</option>').join('');select.value=data.profile.user_id;selected=data.profile.user_id;select.onchange=()=>{selected=select.value;void load();};document.getElementById('masterProgress').hidden=false;if(document.getElementById('includeArchivedProgress'))return;const archive=document.createElement('label');archive.className='progress-archive-toggle';archive.innerHTML='<input id="includeArchivedProgress" type="checkbox"> Include progress from before resets';select.insertAdjacentElement('afterend',archive);document.getElementById('includeArchivedProgress').onchange=()=>void load();}catch(error){document.getElementById('progressMessage').textContent=error.message;}});
document.getElementById('loadMoreProgress').onclick=()=>void load(true);
document.getElementById('inviteForm').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),message=document.getElementById('inviteMessage');button.disabled=true;try{await request('',{method:'POST',body:JSON.stringify({action:'invite',email:document.getElementById('inviteEmail').value.trim()})});message.textContent='Invitation sent. The recipient can follow the email link to set up their account.';document.getElementById('inviteEmail').value='';}catch(error){message.textContent=error.message;}finally{button.disabled=false;}};
})();
